#!/bin/sh

# readable file requiered
: ${1:?Please provide a file path}
cat "$1" 1>/dev/null || exit 1

# check first line
head -n 1 "$1" | grep -q '^#!/' || { echo "script without shebang"; exit 2; }

# separator
echo "${2:-#}" | grep -qv '/' && _s='/' \
	|| echo "$2" | grep -qv '#' && _s='#' \
	|| echo "$2" | grep -qv '+' && _s='+' \
	|| echo "$2" | grep -qv '%' && _s='%' \
	|| echo "$2" | grep -qv '!' && _s='!' \
	|| echo "$2" | grep -qv '~' && _s='~'

# extract comments 
##grep -o "${2:-#}.*${3:-$}" "$1" | sed "s${_s}^${2:-#}\\|${3:-  }\$${_s}${_s}g"
grep -o "${2:-#}.*${3:-$}" "$1" | sed "s$_s^${2:-#}$_s$_s" | sed "s$_s${3:-  }\$$_s$_s"

