#!/bin/sh

# readable file requiered
: ${1:?Please provide a file path}
cat "$1" 1>/dev/null || exit 1

# check first line
head -n 1 "$1" | grep -q '^#!/' || { echo "script without shebang"; exit 2; }

# get length of regexp
l=$( grep -o "${2:-#}" "$1" | sort -gu | tail -n 1 )

# extract comments 
grep -o "${2:-#}.*$" "$1" | cut -c $(( ${#l} + 1 ))- 

